#! /usr/bin/env python

import sys, os
import logging

ui = None

def interactive():
    import readline
    import rlcompleter
    readline.parse_and_bind("tab: complete")
    
    import code
    code.interact(local=globals())
    
def main(argv):
    import tvcmd.cli
    
    ui = tvcmd.cli.Cmd()
    ui.load()
    
    # print torrent urls and exit
    if "-t" in argv:
        ui.onecmd("tor *")
    # main execution mode
    else:
        ui.cmdloop()
        
if __name__ == "__main__":
    
    logging.basicConfig(level=logging.INFO)
    
    if os.environ.get("DEBUG"):
        sys.path.insert(0, os.path.dirname(__file__)+"/..")
        logging.basicConfig(level=logging.DEBUG)
    
    main(sys.argv)
    
    if os.environ.get("DEBUG"): interactive()
    
